version: "3"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: "pgpassword"
      POSTGRES_DB: "pgdb"
  manager:
    build: ./manager
      
    image: "manager_project"
    ports:
      - "5432:5432"
    depends_on:
      - "db"
